### ISSUE TITLE
Report some issues

### ISSUE THREAD

**Issue by yosukehara** [NVIDIA-AI-IOT/Deepstream-Dewarper-App#2]
I've executed this app however I've faced some issues as follows:

1. there is a wrong file path into `deepstream_dewarper_test.c`:

```diff
$ git diff
diff --git a/deepstream_dewarper_test.c b/deepstream_dewarper_test.c
index 9c65f7a..412b52e 100755
--- a/deepstream_dewarper_test.c
+++ b/deepstream_dewarper_test.c
@@ -738,7 +738,7 @@ main (int argc, char *argv[])
   //  "model-engine-file", "/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/Deepstream-Dewarper-App/inference_files/resnet34_peoplenet_pruned.etlt_b1_gpu0_fp16.engine",
   //  NULL);
   g_object_set (G_OBJECT (nvinfer),
-    "config-file-path", "config_infer_primary_peoplenet.txt",
+    "config-file-path", "inference_files/config_infer_primary_peoplenet.txt",
     //"config-file-path", "/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/Deepstream-Dewarper-App/config_infer_primary_peoplenet.txt",
     NULL);
```

2. Failed to parse UFF model:

```
ERROR: [TRT]: Parameter check failed at: ../builder/Network.cpp::addInput::992, condition: isValidDims(dims, hasImplicitBatchDimension())
ERROR: [TRT]: UFFParser: Failed to parseInput for node input_1
ERROR: [TRT]: UffParser: Parser error: input_1: Failed to parse node - Invalid Tensor found at node input_1
parseModel: Failed to parse UFF model
ERROR: failed to build network since parsing model errors.
ERROR: Failed to create network using custom network creation function
ERROR: Failed to get cuda engine from custom library API
0:00:02.153209672 16358   0x559ea0f410 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<nvinfer0> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1736> [UID = 1]: build engine file failed
```

Then I fixed `inference_files/config_infer_primary_peoplenet.txt` as bellow:

```diff
diff --git a/inference_files/config_infer_primary_peoplenet.txt b/inference_files/config_infer_primary_peoplenet.txt
index e27eea6..bda1ed3 100755
--- a/inference_files/config_infer_primary_peoplenet.txt
+++ b/inference_files/config_infer_primary_peoplenet.txt
@@ -24,18 +24,18 @@
 gpu-id=0
 net-scale-factor=0.0039215697906911373
 tlt-model-key=tlt_encode
-#tlt-encoded-model=../../models/tlt_pretrained_models/peoplenet/resnet34_peoplenet_pruned.etlt
 tlt-encoded-model=resnet34_peoplenet_pruned.etlt
-labelfile-path=labels_peoplenet.txt
-#model-engine-file=../../models/tlt_pretrained_models/peoplenet/resnet34_peoplenet_pruned.etlt_b1_gpu0_fp16.engine
-model-engine-file=/home/ds_root/peoplenet/resnet34_peoplenet_pruned.etlt_b1_gpu0_fp16.engine
+labelfile-path=labels.txt
+model-engine-file=resnet34_peoplenet_pruned.etlt_b1_gpu0_int8.engine
+
 input-dims=3;544;960;0
 uff-input-blob-name=input_1
 batch-size=1
 process-mode=1
 model-color-format=0
 ## 0=FP32, 1=INT8, 2=FP16 mode
-network-mode=2
+network-mode=1
+
 num-detected-classes=1
 cluster-mode=1
 interval=0
```

Then I've faced "Segmentation fault" after executing this application.

3. Segmentation fault:

```bash
$ ./deepstream-dewarper-app 3 1 \
    file:///opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/Deepstream-Dewarper-App/sample_office.mp4 \
    6 \
    one_config_dewarper.txt
```

LOG:

```
Running...
Decodebin child added: qtdemux0
Decodebin child added: multiqueue0
Decodebin child added: aacparse0

(deepstream-dewarper-app:16382): GStreamer-WARNING **: 21:29:17.680: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstlibav.so': /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

(deepstream-dewarper-app:16382): GStreamer-WARNING **: 21:29:17.700: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstlibav.so': /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
Decodebin child added: faad0
Decodebin child added: h264parse0
Decodebin child added: capsfilter1
Decodebin child added: nvv4l2decoder0
Opening in BLOCKING MODE
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
In cb_newpad
In cb_newpad
Segmentation fault (core dumped)
```

- Device: Jetson Xavier NX
- Deepstream SDK 5.1

It would be nice if you have solutions.
Thank you.

**Comment by MikyasDesta** [comment]
Hi @yosukehara , thanks for reporting these issues. The first two are solved on the latest update. For the segmentation fault issue, I  run the app again and it's working fine. But I will see if I can reproduce your error with different settings. You should hear from me soon. What is the jetpack version you are using?

**Comment by yosukehara** [comment]
> Hi @yosukehara , thanks for reporting these issues. The first two are solved on the latest update. For the segmentation fault issue, I run the app again and it's working fine. But I will see if I can reproduce your error with different settings. You should hear from me soon. 

Thank you for your support. But I still have the same situation.

> What is the jetpack version you are using?

I'm using the latest version, 4.5.1.

Thank you.

**Comment by MikyasDesta** [comment]
Hi @yosukehara , sorry for the late reply. Can you please try it now. The issue was related to the OSD_SINK_PAD_BUFFER.  I tried it on different platforms and it seems to be working now. Please let me know if you  still have an issue. And thanks for pointing it out.

**Comment by yosukehara** [comment]
@MikyasDesta Thanks a lot. It works fine.
